# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitleaks < Formula
  desc "Gitlekas by UCMP"
  homepage "https://github.com/heechankim-gitleaks/gitleaks"
  version "8.18.0-lgu1.7"
  license "mit"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/heechankim-gitleaks/gitleaks/releases/download/v8.18.0-lgu1.7/gitleaks_Darwin_arm64.tar.gz"
      sha256 "e949adfd6e1e81e2659d2e2018b63b64b84578a6e1828a3ffa51eede9a1c7ba0"

      def install
        bin.install "gitleaks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/heechankim-gitleaks/gitleaks/releases/download/v8.18.0-lgu1.7/gitleaks_Darwin_x86_64.tar.gz"
      sha256 "5c72042afe62795a8adfda9d012e49d741da077a95e459f933f561677b05903b"

      def install
        bin.install "gitleaks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/heechankim-gitleaks/gitleaks/releases/download/v8.18.0-lgu1.7/gitleaks_Linux_armv6.tar.gz"
      sha256 "c665315482caced587821abed7bc40d682c537a4010daf394f936598efd3b9ec"

      def install
        bin.install "gitleaks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heechankim-gitleaks/gitleaks/releases/download/v8.18.0-lgu1.7/gitleaks_Linux_arm64.tar.gz"
      sha256 "338155fde2b268114cafc7151fb0604f3a2ebc644315d01866a1907bd815e1a8"

      def install
        bin.install "gitleaks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/heechankim-gitleaks/gitleaks/releases/download/v8.18.0-lgu1.7/gitleaks_Linux_x86_64.tar.gz"
      sha256 "45ddfcbd2b054d6fccbdc5a7719750f12cfecaf8c770dfa36c25defd9baeeb77"

      def install
        bin.install "gitleaks"
      end
    end
  end
end
