# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Gitleaks < Formula
  desc "Gitlekas by UCMP"
  homepage "https://github.com/heechankim-gitleaks/gitleaks"
  version "8.18.0-lgu1.16"
  license "mit"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/heechankim-gitleaks/gitleaks/releases/download/v8.18.0-lgu1.16/gitleaks_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9ca2429cad194713fa6183cfab7c3ce64f949afb17280a1d1f332e2d2a83781a"

      def install
        bin.install "gitleaks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/heechankim-gitleaks/gitleaks/releases/download/v8.18.0-lgu1.16/gitleaks_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4140bc8c55cb80c15eda937604b20c8b822f9f317f1131aae3478fee1e6afefd"

      def install
        bin.install "gitleaks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/heechankim-gitleaks/gitleaks/releases/download/v8.18.0-lgu1.16/gitleaks_Linux_armv6.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fb99a750dc1ae921caa6d0b616a2301e61684df2905ede61a79a6519b6945a1d"

      def install
        bin.install "gitleaks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heechankim-gitleaks/gitleaks/releases/download/v8.18.0-lgu1.16/gitleaks_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fbebaaa2d03e111d1fbdcdd1dbd7fd1f84365fa04b99361285a365d2066556f5"

      def install
        bin.install "gitleaks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/heechankim-gitleaks/gitleaks/releases/download/v8.18.0-lgu1.16/gitleaks_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bf3b1f4a900ea2cfb19391d7e4cf88e7ffdfd12a613b422a22437a0e653086a5"

      def install
        bin.install "gitleaks"
      end
    end
  end
end
